  Settings-Global:
    # languages en_En,ru_Ru...
    default-language: en_EN
    economy-enable: false

  Claim: # Forced claim options
    item: 'feather'
    claims-limit: 5

    start-blocks: 225
    blocks-per-tick: 4
    tick-time: 1

    min-claim-size: 10
    max-claim-size: 256

    worlds-enable:
      - world

  Global: # Settings that affect the whole server, not just claims
    EndermenMoveBlocks: false
    SilverfishBreakBlocks: false
    RabbitsEatCrops: false

  Placeholders:
    enable-flag: '&aenable'
    disable-flag:  '&cdisable'
    exapmle-color: '<#12345>'
